[build-system]
requires = [
    "setuptools",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "easycheml"
authors = [{name = "AnandSahu", email = "anandsahuofficial@gmail.com"}]
dynamic = ["version", "description"]
